### ISSUE TITLE
Improve Wallet.md

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#555]
Wallet.md seems outdated, and once we re-structure stuff in #550 would be good to explain the internal wallet as a concept better.

- [x] Remove note about keys since it's no longer relevant
- [x] Better explain what's the wallet and how it works, why is it better and what problems it solves
- [x] Move `Advanced Settings` into `Send` 
- [x] Create sign a transaction section in `Send` section and move all `sign with as children`
- [x] Create /wallet img folder and replace legacy images with new ones
- [ ] convert `.PNG` to `.png`
- [ ] Document PSBT 
- [ ] Document Settings tab related #482  
- [ ] Document Coin Selection related #476
- [ ] Document Camera scan icon in send tab #477
